"""vLLM OpenAI-compatible inference path for the desktop agent.

This path mirrors the request/response shape used by yidong72/cua_demo:
direct HTTP calls to a vLLM `/v1/chat/completions` endpoint, SSE streaming,
and `reasoning_content` parsed from the streamed delta payload generated by
vLLM's `nemotron_v3` reasoning parser.
"""

from __future__ import annotations

import asyncio
import json
from typing import Optional

import httpx
from loguru import logger

from server.agent import DeltaCallback, NemotronAgent, ParsedStep, _Turn, parse_response


class VllmInferenceAgent(NemotronAgent):
    """Desktop automation agent powered by a local or remote vLLM endpoint."""

    async def step(
        self,
        instruction: str,
        screenshot_png: bytes,
        screen_size: tuple[int, int],
        *,
        delta_callback: Optional[DeltaCallback] = None,
        client: Optional[httpx.AsyncClient] = None,
    ) -> ParsedStep:
        messages = self.build_messages(instruction, screenshot_png)
        endpoint = self.api_base.rstrip("/") + "/chat/completions"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {self.api_key}",
        }

        max_retry = max(1, self.max_retry)
        last_error = "unknown"
        parsed: Optional[ParsedStep] = None
        owns_client = client is None
        client = client or httpx.AsyncClient(
            timeout=self.model_attempt_timeout + 5,
            verify=False,
        )

        try:
            for attempt in range(max_retry):
                temperature = self.temperature if attempt == 0 else max(0.2, self.temperature)
                payload = {
                    "model": self.model,
                    "messages": messages,
                    "temperature": temperature,
                    "top_p": self.top_p,
                    "max_tokens": self.max_tokens,
                }
                payload.update(self.build_extra_body())

                if delta_callback is not None and attempt > 0:
                    try:
                        await delta_callback(
                            f"\n\n[retry {attempt + 1}/{max_retry}: {last_error}]\n\n",
                            "",
                        )
                    except Exception:
                        pass

                if delta_callback is not None:
                    try:
                        await delta_callback(
                            (
                                f"\n\n[vLLM model attempt {attempt + 1}/{max_retry}; "
                                f"timeout {self.model_attempt_timeout:g}s]\n\n"
                            ),
                            "",
                        )
                    except Exception:
                        pass

                try:
                    logger.info(
                        "vLLM model attempt {}/{} (endpoint={}, timeout={}s, temperature={})",
                        attempt + 1,
                        max_retry,
                        endpoint,
                        self.model_attempt_timeout,
                        temperature,
                    )

                    if delta_callback is None:
                        content, reasoning, finish_reason = await asyncio.wait_for(
                            self._post_completion(client, endpoint, payload, headers),
                            timeout=self.model_attempt_timeout,
                        )
                    else:
                        payload["stream"] = True
                        content, reasoning, finish_reason = await asyncio.wait_for(
                            self._stream_completion(
                                client,
                                endpoint,
                                payload,
                                headers,
                                delta_callback,
                            ),
                            timeout=self.model_attempt_timeout,
                        )

                    if finish_reason not in (None, "stop"):
                        last_error = f"unexpected finish_reason={finish_reason}"
                        logger.warning(
                            "vLLM attempt {}/{}: {}; retrying",
                            attempt + 1,
                            max_retry,
                            last_error,
                        )
                        if attempt + 1 < max_retry:
                            await asyncio.sleep(self.retry_sleep)
                        continue

                    parsed = parse_response(
                        content,
                        reasoning,
                        screen_size[0],
                        screen_size[1],
                        thinking=self.thinking,
                    )
                    if parsed.status != "error":
                        break
                    last_error = parsed.error or "parse error"
                    logger.warning(
                        "vLLM attempt {}/{}: parse error: {}; retrying",
                        attempt + 1,
                        max_retry,
                        last_error,
                    )
                    if attempt + 1 < max_retry:
                        await asyncio.sleep(self.retry_sleep)

                except asyncio.TimeoutError:
                    last_error = f"model timed out after {self.model_attempt_timeout:g}s"
                    logger.warning(
                        "vLLM attempt {}/{}: {}; retrying",
                        attempt + 1,
                        max_retry,
                        last_error,
                    )
                    if attempt + 1 < max_retry:
                        await asyncio.sleep(self.retry_sleep)

                except Exception as exc:
                    last_error = f"request failed: {exc}"
                    logger.error(
                        "vLLM attempt {}/{}: {}; retrying",
                        attempt + 1,
                        max_retry,
                        last_error,
                    )
                    if attempt + 1 < max_retry:
                        await asyncio.sleep(self.retry_sleep)

        finally:
            if owns_client:
                await client.aclose()

        if parsed is None or parsed.status == "error":
            return ParsedStep(
                status="error",
                error=f"all {max_retry} attempts failed: {last_error}",
            )

        if parsed.status in {"continue", "wait"}:
            self.history.append(
                _Turn(
                    screenshot_png=screenshot_png,
                    thought=parsed.thought,
                    action=parsed.action,
                )
            )
        return parsed

    async def _post_completion(
        self,
        client: httpx.AsyncClient,
        endpoint: str,
        payload: dict,
        headers: dict,
    ) -> tuple[str, str, Optional[str]]:
        resp = await client.post(endpoint, json=payload, headers=headers)
        if resp.status_code != 200:
            raise RuntimeError(f"vLLM HTTP {resp.status_code}: {resp.text[:400]}")
        body = resp.json()
        choice = (body.get("choices") or [{}])[0]
        message = choice.get("message") or {}
        return (
            message.get("content") or "",
            message.get("reasoning_content") or message.get("reasoning") or "",
            choice.get("finish_reason"),
        )

    async def _stream_completion(
        self,
        client: httpx.AsyncClient,
        endpoint: str,
        payload: dict,
        headers: dict,
        delta_callback: DeltaCallback,
    ) -> tuple[str, str, Optional[str]]:
        reasoning_buf: list[str] = []
        content_buf: list[str] = []
        finish_reason: Optional[str] = None

        async with client.stream("POST", endpoint, json=payload, headers=headers) as resp:
            if resp.status_code != 200:
                err_body = (await resp.aread()).decode("utf-8", errors="replace")
                raise RuntimeError(f"vLLM stream HTTP {resp.status_code}: {err_body[:400]}")

            async for raw in resp.aiter_lines():
                if not raw or not raw.startswith("data:"):
                    continue
                data = raw[len("data:") :].strip()
                if not data or data == "[DONE]":
                    continue
                try:
                    chunk = json.loads(data)
                except json.JSONDecodeError:
                    logger.warning("vLLM stream returned non-JSON data chunk: {!r}", data[:200])
                    continue

                choices = chunk.get("choices") or []
                if not choices:
                    continue
                choice = choices[0]
                delta = choice.get("delta") or {}
                r_delta = delta.get("reasoning_content") or delta.get("reasoning") or ""
                c_delta = delta.get("content") or ""

                if r_delta:
                    reasoning_buf.append(r_delta)
                if c_delta:
                    content_buf.append(c_delta)
                if r_delta or c_delta:
                    try:
                        await delta_callback(r_delta, c_delta)
                    except Exception:
                        logger.warning("delta_callback raised; continuing vLLM stream")

                if choice.get("finish_reason"):
                    finish_reason = choice["finish_reason"]

        return "".join(content_buf), "".join(reasoning_buf), finish_reason
